services:
  postgres:
    image: postgres:latest
    container_name: itso-quiz-bee-pg
    environment:
      POSTGRES_USER: itso
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itso-quiz-bee
    ports:
      - "5432:5432"
    volumes:
      - itso-quiz-bee-pg:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack:latest
    container_name: itso-quiz-bee-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - itso-quiz-bee-redis:/data

volumes:
  itso-quiz-bee-pg:
  itso-quiz-bee-redis:
